### ISSUE TITLE
Invalid wave file, the size is too small.

### ISSUE THREAD

**Issue by atis-s** [sandrohanea/whisper.net#140]
Hi, 
I am trying to convert simple one sentence file in Latvian.
File is 193006 bytes after conversion to 16k but then I get this exception: 
`Exception: Whisper.net.Wave.CorruptedWaveException: Invalid wave file, the size is too small.
   at Whisper.net.Wave.WaveParser.<InternalInitialize>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Whisper.net.Wave.WaveParser.<GetAvgSamplesAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Whisper.net.WhisperProcessor.<ProcessAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.GetResult(Int16 token)
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at AutomateWallCreation.GPTAssistants.Services.SpeachToTextService.<TranscriptAudio>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at AutomateWallCreation.GPTAssistants.Services.SpeachToTextService.<TranscriptAudio>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at AutomateWallCreation.Controller.ChatInputController.<TranscriptAudioAsync>d__5.MoveNext()`

**Comment by sandrohanea** [comment]
Hello @atis-s ,
I suspect you are sending a stream which is already consumed without resetting the position to 0, first if you are sure that the file is 193006 bytes.

If that is the case, please, call 

```
myStream.Seek(0, SeekOrigin.Begin)
```

before passing the stream to the WhisperProcessor
