### ISSUE TITLE
Error loading model

### ISSUE THREAD

**Issue by Mrgaton** [sandrohanea/whisper.net#186]
System.Exception
  HResult=0x80131500
  Mensaje = Failed to load native whisper library. Error: %1 no es una aplicación Win32 válida
  Origen = Whisper.net
  Seguimiento de la pila:
   at Whisper.net.WhisperFactory..ctor(IWhisperProcessorModelLoader loader, Boolean delayInit, String libraryPath, Boolean bypassLoading)
   at Whisper.net.WhisperFactory.FromPath(String path, Boolean delayInitialization, String libraryPath, Boolean bypassLoading, Boolean useGpu)
   at SpechToText.Program.<Thread>d__1.MoveNext() in SpechToText\SpechToText\Program.cs:line 35
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at SpechToText.Program.Main(String[] args) in SpechToText\SpechToText\Program.cs:line 17

**Comment by Mrgaton** [comment]
Im on windows and vc redist is already installed

**Comment by b97ha** [comment]
I facing this issue too 
the library works fine on my local machine, but I get this error when try to run it on Windows Server 
"Failed to load native whisper library. Error: A dynamic link library (DLL) initialization routine failed."
I am using Whisper Inside Background Worker Service.
Any help, please?

**Comment by Mrgaton** [comment]
I get the issue on my main windows machine

**Comment by Mrgaton** [comment]
@sandrohanea  please take a look i cant use the lib

**Comment by Mrgaton** [comment]
> I facing this issue too the library works fine on my local machine, but I get this error when try to run it on Windows Server "Failed to load native whisper library. Error: A dynamic link library (DLL) initialization routine failed." I am using Whisper Inside Background Worker Service. Any help, please?

Try using NET 8 instead of framework worked for me

**Comment by jkkgrk** [comment]
I had a similar error with Runtime.Cublas, and it was due to misconfigured CUDA environment variables.

**Comment by Mrgaton** [comment]
it worked for me after not usin net framework

**Comment by sandrohanea** [comment]
this means that native library cannot be loaded. It might be that you don't have the necessary dependencies or what happened to me before was to call the project "Whisper.net.Runtime" or "Openvino" creating a dll that is not a native dll but a dotnet dll with the same name as one of the dependencies.
