### ISSUE TITLE
[1.7.0+] Cannot load the library on this platform using NativeLibrary - Linux (Docker)

### ISSUE THREAD

**Issue by bvdcode** [sandrohanea/whisper.net#249]
Before upgrading I was using version 1.5.0 which worked fine on Linux container but when upgrading to 1.7.0+ I got the error below:

1.7.0:
```
System.Exception: Failed to load native whisper library. Error: Unknown error
   at Whisper.net.WhisperFactory..ctor(IWhisperProcessorModelLoader loader, Boolean delayInit)
   at Whisper.net.WhisperFactory.FromPath(String path, Boolean delayInitialization)
   at WhisperBot.Bot.CreateWhisperAsync(CancellationToken token) in /src/Bot.cs:line 123
Unhandled exception. System.Exception: Failed to load native whisper library. Error: Unknown error
   at Whisper.net.WhisperFactory..ctor(IWhisperProcessorModelLoader loader, Boolean delayInit)
   at Whisper.net.WhisperFactory.FromPath(String path, Boolean delayInitialization)
   at WhisperBot.Bot.CreateWhisperAsync(CancellationToken token) in /src/Bot.cs:line 123
   at WhisperBot.Bot.StartAsync(CancellationToken token) in /src/Bot.cs:line 29
   at WhisperBot.Program.Main() in /src/Program.cs:line 20
   at WhisperBot.Program.<Main>()
```

1.7.2-preview2
```
System.Exception: Failed to load native whisper library. Error: Cannot load the library on this platform using NativeLibrary
   at Whisper.net.WhisperFactory.CheckLibraryLoaded()
   at Whisper.net.WhisperFactory..ctor(IWhisperProcessorModelLoader loader, Boolean delayInit)
   at Whisper.net.WhisperFactory.FromPath(String path, Boolean delayInitialization)
   at WhisperBot.Bot.CreateWhisperAsync(CancellationToken token) in /src/Bot.cs:line 123
Unhandled exception. System.Exception: Failed to load native whisper library. Error: Cannot load the library on this platform using NativeLibrary
   at Whisper.net.WhisperFactory.CheckLibraryLoaded()
   at Whisper.net.WhisperFactory..ctor(IWhisperProcessorModelLoader loader, Boolean delayInit)
   at Whisper.net.WhisperFactory.FromPath(String path, Boolean delayInitialization)
   at WhisperBot.Bot.CreateWhisperAsync(CancellationToken token) in /src/Bot.cs:line 123
   at WhisperBot.Bot.StartAsync(CancellationToken token) in /src/Bot.cs:line 29
   at WhisperBot.Program.Main() in /src/Program.cs:line 20
   at WhisperBot.Program.<Main>()
```

Debian GNU/Linux 12 (bookworm) - Docker image [mcr.microsoft.com/dotnet/runtime:8.0](https://hub.docker.com/r/microsoft/dotnet-runtime)

I will provide any information that can help you understand the problem, just let me know, thanks a lot!

**Comment by bvdcode** [comment]
I'm investigating issue #11, maybe it's related. The only confusing thing is that it worked fine in 1.5.0

**Comment by bvdcode** [comment]
I tried adding
```bash
apt-get update && apt-get install -y libstdc++6
```
but it didn't help

**Comment by bvdcode** [comment]
Am I correct in understanding that this error is only related to `libstdc++6`?

**Comment by sandrohanea** [comment]
Hello @bvdcode ,
No, that is not the only reason why you cam have that issue, but any issue with dlopen for libggml or libwhisper can cause it. For better diagnosis, you can add logging (e.g to console) to check exactly which of them cannot be loaded. Once you did that, you can use "ldd" tool on linux to find the dependencies that you might miss on your system. Can you try these and update us here with the discovery?

Thank you!

**Comment by sandrohanea** [comment]
Also, there was an issue with the Linux build in 1.7.0, see #222 but it should be fixed in any version higher than 1.7.0.

Please, ensure you clean/rebuild if you used that version(1.7.0) to not have some old library copied to your output path.

**Comment by dfengpo** [comment]
I use whisper.net.runtime.cuda\1.7.1，the error also.
![image](https://github.com/user-attachments/assets/0df04e2c-ef9f-4acb-ba42-c772bc699474)

**Comment by kaniosm** [comment]
same for me...
I copied libggml.so and libwhisper.so files from runtimes/cuda/linux-x64 to the root directory, which works when I debug on Linux, but the same approach will not work on docker.
My docker base image is nvidia/cuda:12.1.1-cudnn8-devel-ubuntu22.04
I'm installing dotnet, aspnetcore, libstdc++6 and zlib1g, and copy the files as described above, below you can find the relevant sections of my docker file:

RUN apt install -y dotnet-sdk-8.0
RUN apt install -y aspnetcore-runtime-8.0
RUN apt install -y dotnet-runtime-8.0
RUN apt install zlib1g
RUN apt-get install -y libstdc++6


FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
COPY --from=publish /app/publish/runtimes/cuda/linux-x64/*.so .
ENTRYPOINT ["dotnet", "SpeechToText.dll"]

**Comment by sandrohanea** [comment]
Hey @kaniosm ,
You shouldn't copy the runtimes manually; they are already where they should be. 
Be sure you have Cuda toolkit with cudart and cublas installed in the VM: https://github.com/sandrohanea/whisper.net/issues/257
You can also enable full logging to see what library is loaded and why.

Just call `LogProvider.AddConsoleLogging(minLevel: WhisperLogLevel.Debug)` before any WhisperFactory is created.

**Comment by kaniosm** [comment]
Thanks for the update @sandrohanea.

I can confirm that the approach I described above works for version 1.7.0.
I had the same issue, that's why I copied the files.

**Comment by bvdcode** [comment]
@kaniosm, You can use this one:
```csharp
LogProvider.Instance.OnLog += (sender, args) =>
{
    if (string.IsNullOrWhiteSpace(args))
    {
        return;
    }
    Console.WriteLine(args);
};
```

**Comment by kaniosm** [comment]
thx for the update @bvdcode... done it already! really appreciate it.

**Comment by kaniosm** [comment]
I'm not getting anything from whisper logger... I'm listing here the output from my logger in case this helps someone:

System.IO.FileNotFoundException: Native Library not found in default paths.Verify you have have included the native Whisper library in your application, or install the default libraries with the Whisper.net.Runtime NuGet.
   at Whisper.net.LibraryLoader.NativeLibraryLoader.LoadLibraryComponent()
   at Whisper.net.LibraryLoader.NativeLibraryLoader.LoadNativeLibrary()
   at Whisper.net.WhisperFactory.<>c.<.cctor>b__10_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location ---
   at System.Lazy`1.CreateValue()
   at Whisper.net.WhisperFactory..ctor(IWhisperProcessorModelLoader loader, Boolean delayInit)
   at Whisper.net.WhisperFactory.FromPath(String path, Boolean delayInitialization)
   at SpeechToText.Services.WhisperService..ctor(ILogger`1 logger) in /src/Services/WhisperService.cs:line 28
   at InvokeStub_WhisperService..ctor(Object, Span`1)
