### ISSUE TITLE
.NET 9.0 Fails to build Whisper.net.Demo

### ISSUE THREAD

**Issue by steve3p0** [sandrohanea/whisper.net#311]
**ChatGPT discussion**
 - [ ] I asked [Whisper.net Helper][(https://chatgpt.com/share/676eb704-9cd0-800b-b1fe-28cf70f543d1](https://chatgpt.com/share/676eb704-9cd0-800b-b1fe-28cf70f543d1)) and it couldn't help me, here is the discussion link: 

**Describe the bug**
Cloned latest Whisper.net.Runtime and Whisper.net.Demo gives me 36 errors:

![image](https://github.com/user-attachments/assets/5954836d-84af-44a2-8d67-3f4957dc3f77)

```
Severity	Code	Description	Project	File	Line	Suppression State	Details
Message (active)	CA1050	Types are declared in namespaces to prevent name collisions and as a way to organize related types in an object hierarchy.	Whisper.net.Demo (net9.0)	C:\workspace\___skunks\whisper.net\Whisper.net.Demo\Program.cs	85		
Error (active)	MSB3030	Could not copy the file "C:\workspace\___skunks\whisper.net\runtimes\Whisper.net.Runtime\win-x86\whisper.dll" because it was not found.	Whisper.net.Demo (net9.0)	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	5322		
Error (active)	MSB3030	Could not copy the file "C:\workspace\___skunks\whisper.net\runtimes\Whisper.net.Runtime\win-x86\ggml-whisper.dll" because it was not found.	Whisper.net.Demo (net9.0)	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	5322		
Error (active)	MSB3030	Could not copy the file "C:\workspace\___skunks\whisper.net\runtimes\Whisper.net.Runtime\win-x86\ggml-cpu-whisper.dll" because it was not found.	Whisper.net.Demo (net9.0)	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	5322		
Error (active)	MSB3030	Could not copy the file "C:\workspace\___skunks\whisper.net\runtimes\Whisper.net.Runtime\win-x86\ggml-base-whisper.dll" because it was not found.	Whisper.net.Demo (net9.0)	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	5322		
Error (active)	MSB3030	Could not copy the file "C:\workspace\___skunks\whisper.net\runtimes\Whisper.net.Runtime\win-x64\whisper.dll" because it was not found.	Whisper.net.Demo (net9.0)	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	5322		
Error (active)	MSB3030	Could not copy the file "C:\workspace\___skunks\whisper.net\runtimes\Whisper.net.Runtime\win-x64\ggml-whisper.dll" because it was not found.	Whisper.net.Demo (net9.0)	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	5322		
Error (active)	MSB3030	Could not copy the file "C:\workspace\___skunks\whisper.net\runtimes\Whisper.net.Runtime\win-x64\ggml-cpu-whisper.dll" because it was not found.	Whisper.net.Demo (net9.0)	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	5322		
Error (active)	MSB3030	Could not copy the file "C:\workspace\___skunks\whisper.net\runtimes\Whisper.net.Runtime\win-x64\ggml-base-whisper.dll" because it was not found.	Whisper.net.Demo (net9.0)	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	5322		
Error (active)	MSB3030	Could not copy the file "C:\workspace\___skunks\whisper.net\runtimes\Whisper.net.Runtime\win-arm64\whisper.dll" because it was not found.	Whisper.net.Demo (net9.0)	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	5322		
Error (active)	MSB3030	Could not copy the file "C:\workspace\___skunks\whisper.net\runtimes\Whisper.net.Runtime\win-arm64\ggml-whisper.dll" because it was not found.	Whisper.net.Demo (net9.0)	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	5322		
Error (active)	MSB3030	Could not copy the file "C:\workspace\___skunks\whisper.net\runtimes\Whisper.net.Runtime\win-arm64\ggml-cpu-whisper.dll" because it was not found.	Whisper.net.Demo (net9.0)	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	5322		
Error (active)	MSB3030	Could not copy the file "C:\workspace\___skunks\whisper.net\runtimes\Whisper.net.Runtime\win-arm64\ggml-base-whisper.dll" because it was not found.	Whisper.net.Demo (net9.0)	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	5322		
Error (active)	MSB3030	Could not copy the file "C:\workspace\___skunks\whisper.net\runtimes\Whisper.net.Runtime\macos-x64\libwhisper.dylib" because it was not found.	Whisper.net.Demo (net9.0)	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	5322		
Error (active)	MSB3030	Could not copy the file "C:\workspace\___skunks\whisper.net\runtimes\Whisper.net.Runtime\macos-x64\libggml-whisper.dylib" because it was not found.	Whisper.net.Demo (net9.0)	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	5322		
Error (active)	MSB3030	Could not copy the file "C:\workspace\___skunks\whisper.net\runtimes\Whisper.net.Runtime\macos-x64\libggml-cpu-whisper.dylib" because it was not found.	Whisper.net.Demo (net9.0)	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	5322		
Error (active)	MSB3030	Could not copy the file "C:\workspace\___skunks\whisper.net\runtimes\Whisper.net.Runtime\macos-x64\libggml-blas-whisper.dylib" because it was not found.	Whisper.net.Demo (net9.0)	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	5322		
Error (active)	MSB3030	Could not copy the file "C:\workspace\___skunks\whisper.net\runtimes\Whisper.net.Runtime\macos-x64\libggml-base-whisper.dylib" because it was not found.	Whisper.net.Demo (net9.0)	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	5322		
Error (active)	MSB3030	Could not copy the file "C:\workspace\___skunks\whisper.net\runtimes\Whisper.net.Runtime\macos-arm64\libwhisper.dylib" because it was not found.	Whisper.net.Demo (net9.0)	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	5322		
Error (active)	MSB3030	Could not copy the file "C:\workspace\___skunks\whisper.net\runtimes\Whisper.net.Runtime\macos-arm64\libggml-whisper.dylib" because it was not found.	Whisper.net.Demo (net9.0)	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	5322		
Error (active)	MSB3030	Could not copy the file "C:\workspace\___skunks\whisper.net\runtimes\Whisper.net.Runtime\macos-arm64\libggml-metal-whisper.dylib" because it was not found.	Whisper.net.Demo (net9.0)	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	5322		
Error (active)	MSB3030	Could not copy the file "C:\workspace\___skunks\whisper.net\runtimes\Whisper.net.Runtime\macos-arm64\libggml-cpu-whisper.dylib" because it was not found.	Whisper.net.Demo (net9.0)	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	5322		
Error (active)	MSB3030	Could not copy the file "C:\workspace\___skunks\whisper.net\runtimes\Whisper.net.Runtime\macos-arm64\libggml-blas-whisper.dylib" because it was not found.	Whisper.net.Demo (net9.0)	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	5322		
Error (active)	MSB3030	Could not copy the file "C:\workspace\___skunks\whisper.net\runtimes\Whisper.net.Runtime\macos-arm64\libggml-base-whisper.dylib" because it was not found.	Whisper.net.Demo (net9.0)	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	5322		
Error (active)	MSB3030	Could not copy the file "C:\workspace\___skunks\whisper.net\runtimes\Whisper.net.Runtime\linux-x64\libwhisper.so" because it was not found.	Whisper.net.Demo (net9.0)	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	5322		
Error (active)	MSB3030	Could not copy the file "C:\workspace\___skunks\whisper.net\runtimes\Whisper.net.Runtime\linux-x64\libggml-whisper.so" because it was not found.	Whisper.net.Demo (net9.0)	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	5322		
Error (active)	MSB3030	Could not copy the file "C:\workspace\___skunks\whisper.net\runtimes\Whisper.net.Runtime\linux-x64\libggml-cpu-whisper.so" because it was not found.	Whisper.net.Demo (net9.0)	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	5322		
Error (active)	MSB3030	Could not copy the file "C:\workspace\___skunks\whisper.net\runtimes\Whisper.net.Runtime\linux-x64\libggml-base-whisper.so" because it was not found.	Whisper.net.Demo (net9.0)	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	5322		
Error (active)	MSB3030	Could not copy the file "C:\workspace\___skunks\whisper.net\runtimes\Whisper.net.Runtime\linux-arm\libwhisper.so" because it was not found.	Whisper.net.Demo (net9.0)	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	5322		
Error (active)	MSB3030	Could not copy the file "C:\workspace\___skunks\whisper.net\runtimes\Whisper.net.Runtime\linux-arm\libggml-whisper.so" because it was not found.	Whisper.net.Demo (net9.0)	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	5322		
Error (active)	MSB3030	Could not copy the file "C:\workspace\___skunks\whisper.net\runtimes\Whisper.net.Runtime\linux-arm\libggml-cpu-whisper.so" because it was not found.	Whisper.net.Demo (net9.0)	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	5322		
Error (active)	MSB3030	Could not copy the file "C:\workspace\___skunks\whisper.net\runtimes\Whisper.net.Runtime\linux-arm\libggml-base-whisper.so" because it was not found.	Whisper.net.Demo (net9.0)	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	5322		
Error (active)	MSB3030	Could not copy the file "C:\workspace\___skunks\whisper.net\runtimes\Whisper.net.Runtime\linux-arm64\libwhisper.so" because it was not found.	Whisper.net.Demo (net9.0)	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	5322		
Error (active)	MSB3030	Could not copy the file "C:\workspace\___skunks\whisper.net\runtimes\Whisper.net.Runtime\linux-arm64\libggml-whisper.so" because it was not found.	Whisper.net.Demo (net9.0)	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	5322		
Error (active)	MSB3030	Could not copy the file "C:\workspace\___skunks\whisper.net\runtimes\Whisper.net.Runtime\linux-arm64\libggml-cpu-whisper.so" because it was not found.	Whisper.net.Demo (net9.0)	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	5322		
Error (active)	MSB3030	Could not copy the file "C:\workspace\___skunks\whisper.net\runtimes\Whisper.net.Runtime\linux-arm64\libggml-base-whisper.so" because it was not found.	Whisper.net.Demo (net9.0)	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	5322		
Error (active)	MSB3030	Could not copy the file "C:\workspace\___skunks\whisper.net\runtimes\Whisper.net.Runtime\ggml-metal.metal" because it was not found.	Whisper.net.Demo (net9.0)	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	5322	
```	

I added the Whisper.net.Runtime version 1.7.4 from Nuget.

**Comment by sandrohanea** [comment]
Hello @steve3p0 ,
It seems that you're trying to build the demo without having the runtimes in the local path.

You can do one of the following:
 - Remove the local reference to the runtimes from here: https://github.com/sandrohanea/whisper.net/blob/a3ec2f8fa8f19a5fd905dec2368aa16940dd35fd/Whisper.net.Demo/Whisper.net.Demo.csproj#L2
   (just delete or comment out that `Import`)
   If you remove that, ensure that you install Whisper.net.Runtime 1.7.4 from Nuget as you said above.
   
  - Second option if you want to use the local runtimes, you can build all the dylibs using make (or just fork this repo, run the github action for CI and download the artifacts with the built runtimes). In this case, Whisper.net.Runtime nuget reference won't be needed.
  
 Demo is designed to show and run the app locally, but examples are recommended for low-effort running of Whisper scenarios using the nuget version.

**Comment by steve3p0** [comment]
OK.  Option 1 worked!

There is another local reference besides targets for Whisper.net.Runtime that I commented out:

```
<!--<Import Condition="'$(EnableCoreML)' != 'true'" Project="../runtimes/Whisper.net.Runtime/Whisper.net.Runtime.targets" />-->
<Import Condition="'$(EnableCoreML)' == 'true'" Project="../runtimes/Whisper.net.Runtime.CoreML/Whisper.net.Runtime.CoreML.targets" />
```

I left that 2nd one and it works... so, cool!  

**_One more question:_** 
Can I just copy the Whisper.net "project" folder from your solution into my solution and add a reference in my solution's project to it?  I don't need anything else, like whisper.cpp, do I?  In my previous attempt that I got working with Windows, I just pretty merged both solution directories.

**Comment by steve3p0** [comment]
Sandro, 
I'm almost there.  Can you help me with this error:

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error		XAPRAS7023: System.IO.DirectoryNotFoundException: **Could not find a part of the path 'C:\workspace\___skunks\Slide.net\Whisper.net\bin\Debug\net9.0\android-x64\Whisper.net.dll'.**
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Xamarin.Android.Tasks.MonoAndroidHelper.HasMonoAndroidReference(ITaskItem assembly) in /Users/runner/work/1/s/xamarin-android/src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs:line 349
   at Xamarin.Android.Tasks.ProcessAssemblies.SetMetadataForAssemblies(List`1 output, Dictionary`2 symbols) in /Users/runner/work/1/s/xamarin-android/src/Xamarin.Android.Build.Tasks/Tasks/ProcessAssemblies.cs:line 129
   at Xamarin.Android.Tasks.ProcessAssemblies.RunTask() in /Users/runner/work/1/s/xamarin-android/src/Xamarin.Android.Build.Tasks/Tasks/ProcessAssemblies.cs:line 62
   at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 25		 	0		

I've got some warnings that I think explain why I am getting that error.  I have been struggling with making sure that Whisper.net generates the DLL in location that it's expected.  I have no idea where it gets that path.  I mean see parts of it and RIDs, blah, blah.  I don't completely get it.

**Warnings:**

- **MSB3270:** There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "C:\workspace\___skunks\Slide.net\Whisper.net\bin\Debug\net9.0\win-x64\Whisper.net.dll", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project., Slide.net (net9.0-android), MainActivity.cs, line 6

**Message:**

- **IDE0130:** Namespace "Slide.net" does not match folder structure, expected "Slide.net.Platforms.Android", Slide.net (net9.0-android), Microsoft.Common.CurrentVersion.targets, line 2413

**Comment by sandrohanea** [comment]
> **_One more question:_** Can I just copy the Whisper.net "project" folder from your solution into my solution and add a reference in my solution's project to it? I don't need anything else, like whisper.cpp, do I? In my previous attempt that I got working with Windows, I just pretty merged both solution directories.

Why not using the package directly instead of copying the Whisper.net project folder?
Just reference `Whisper.net` project to your solution, same as in the examples: (e.g. [Simple example](https://github.com/sandrohanea/whisper.net/blob/main/examples/Simple/Simple.csproj))



> Sandro, I'm almost there. Can you help me with this error:
> 
> Severity Code Description Project File Line Suppression State Details Error XAPRAS7023: System.IO.DirectoryNotFoundException: **Could not find a part of the path 'C:\workspace___skunks\Slide.net\Whisper.net\bin\Debug\net9.0\android-x64\Whisper.net.dll'.** at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share) at Xamarin.Android.Tasks.MonoAndroidHelper.HasMonoAndroidReference(ITaskItem assembly) in /Users/runner/work/1/s/xamarin-android/src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs:line 349 at Xamarin.Android.Tasks.ProcessAssemblies.SetMetadataForAssemblies(List`1 output, Dictionary`2 symbols) in /Users/runner/work/1/s/xamarin-android/src/Xamarin.Android.Build.Tasks/Tasks/ProcessAssemblies.cs:line 129 at Xamarin.Android.Tasks.ProcessAssemblies.RunTask() in /Users/runner/work/1/s/xamarin-android/src/Xamarin.Android.Build.Tasks/Tasks/ProcessAssemblies.cs:line 62 at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 25 0
> 
> I've got some warnings that I think explain why I am getting that error. I have been struggling with making sure that Whisper.net generates the DLL in location that it's expected. I have no idea where it gets that path. I mean see parts of it and RIDs, blah, blah. I don't completely get it.
> 
> **Warnings:**
> 
> * **MSB3270:** There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "C:\workspace___skunks\Slide.net\Whisper.net\bin\Debug\net9.0\win-x64\Whisper.net.dll", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project., Slide.net (net9.0-android), MainActivity.cs, line 6
> 
> **Message:**
> 
> * **IDE0130:** Namespace "Slide.net" does not match folder structure, expected "Slide.net.Platforms.Android", Slide.net (net9.0-android), Microsoft.Common.CurrentVersion.targets, line 2413


Regarding this error, I'm not sure if I understand whay caused it. Do you have some reproduction steps (e.g. some project where the issue is reproduced? )

**Comment by steve3p0** [comment]
> > **_One more question:_** Can I just copy the Whisper.net "project" folder from your solution into my solution and add a reference in my solution's project to it? I don't need anything else, like whisper.cpp, do I? In my previous attempt that I got working with Windows, I just pretty merged both solution directories.
> 
> Why not using the package directly instead of copying the Whisper.net project folder? Just reference `Whisper.net` project to your solution, same as in the examples: (e.g. [Simple example](https://github.com/sandrohanea/whisper.net/blob/main/examples/Simple/Simple.csproj))

What you are suggesting is to use the pre-compiled builds using nuget, correct?  When I have both Whisper.net and Whisper.net.Runtime added using nuget, IT WORKS!!!! It works on both Windows and Android.  And I assume it will on iPhone.  In fact, you helped me get it to work (THANKS!!!).  See this issue https://github.com/sandrohanea/whisper.net/issues/297.  User @StevePGLS) is my work account.

But alas, I need to modify your code.  **_AND this is what doesn't work on Android._** 

**_On Android, a project reference to your Whisper.net project will result in runtime errors.  But It works on Windows!_**


_So just to be clear:_ 
If I add Whisper.net as a project reference (keeping Whisper.net.Runtime from Nuget), I get a runtime error on Android. But I don't get this error on Windows.  Windows works great with Whisper.net.Rutime version 1.7.4 and your latest Whisper.net code on GitHub (which has a version of 1.7.4 listed in the .csproj file).  But I get the following error on my Android Pixel 8 - API 35 (attached is a log file).

**Error message on Android:**
`[monodroid-assembly] open_from_bundles: failed to load bundled assembly Whisper.net.dll`
Here's the full log:
[Android_Emulator_Win10_log_whisper.net (from project) error.log](https://github.com/user-attachments/files/18275971/Android_Emulator_Win10_log_whisper.net.from.project.error.log)

And here is the code in MainPage.xaml.cs where I call Whisper.  The error happens on the 2nd to last line:

`var factory = WhisperFactory.FromBuffer(bufferedModel); // <<<< ERROR`

**MainPage.xaml.cs**
```
using System.IO;
using Whisper.net;
using Whisper.net.Ggml;

namespace Slide.App
{
    public partial class MainPage : ContentPage
    {
        public MainPage()
        {
            InitializeComponent();

            MainPage.TestWhisperNet();
        }

        public static async void TestWhisperNet()
        {
            // Define the model file name
            const string modelFileName = "ggml-tiny.bin";

            // Open the model file as a stream using MAUI's asset system
            using var stream = await FileSystem.Current.OpenAppPackageFileAsync(modelFileName);

            // Read the stream into a byte array
            using var memoryStream = new MemoryStream();
            await stream.CopyToAsync(memoryStream);
            var bufferedModel = memoryStream.ToArray();

            // Initialize the Whisper factory
 ERROR >>>> var factory = WhisperFactory.FromBuffer(bufferedModel);  // <<<< ERROR
            System.Diagnostics.Debug.WriteLine("Whisper model loaded successfully!");
        }
    }
}
```

Now, I've paired this down to the point that I am just using the out-of-box "Hello, world!" .NET MAUI Blazor sample project.  And I have made some progress.  Before, it was very difficult to get repeatable behavior.  I am getting repeatable behavior now. 

I can consistently compile on the command line.  I first run these commands one time:

```
dotnet workload update
dotnet build -r win-x64
dotnet build -r android-x64
```

Then whenever I make changes, this set of commands seem to work well for me and it consistently compiles:

```
dotnet clean 
dotnet restore
dotnet clean Whisper.net/Whisper.net.csproj
dotnet build Whisper.net/Whisper.net.csproj -r android-x64
dotnet build .\Slide.App\Slide.App.csproj -f net9.0-android -r android-x64
```

> > Sandro, I'm almost there. Can you help me with this error:
>> Severity Code Description Project File Line Suppression State Details Error
> 
> Regarding this error, I'm not sure if I understand whay caused it. Do you have some reproduction steps (e.g. some project where the issue is reproduced? )

This error has been cleared since I went back and started with a fresh copy of the .NET MAUI Blazor sample project solution code.

I also upgraded to .NET MAUI and the .NET Framework from 8.0 to 9.0.  I have much more repeatable behavior with these upgrades and I have tried to make my project code as simple as possible, with the minimum to produce this error.

Here are log files showing it working and not working:
[Android_Emulator_Win10_log_whisper.net (from nuget) works.log](https://github.com/user-attachments/files/18276013/Android_Emulator_Win10_log_whisper.net.from.nuget.works.log)
[Android_Emulator_Win10_log_whisper.net (from project) error.log](https://github.com/user-attachments/files/18276015/Android_Emulator_Win10_log_whisper.net.from.project.error.log)
[Win10_log_whisper.net (from project) works.log](https://github.com/user-attachments/files/18276019/Win10_log_whisper.net.from.project.works.log)

**Comment by sandrohanea** [comment]
Hello @steve3p0 ,
Based on the logs, it seems that you're getting:
![image](https://github.com/user-attachments/assets/112d18d6-3369-4a99-94ce-38145681f312)

That is thrown here: 
https://github.com/sandrohanea/whisper.net/blob/38a817cc5d59fc477c77b0bd8ce690bb7ec10f54/Whisper.net/LibraryLoader/NativeLibraryLoader.cs#L49

Which means that the `Whisper.net` project that you copied was not built with Android runtime (otherwise it would have returned here):

https://github.com/sandrohanea/whisper.net/blob/38a817cc5d59fc477c77b0bd8ce690bb7ec10f54/Whisper.net/LibraryLoader/NativeLibraryLoader.cs#L23

It might be because you are referencing it into some other project (from net8 / net9) that is not built with runtime `net8-android` or `net9-android`.

Example:

 If you have 3 projects:
   `ProjectA` => net9
   `ProjectB` => net9-android
   `Whisper.net`=> net9-android, net9
   
   And you referece Whisper.net in `ProjectA` => it will use the `net9` version (as the `net9-android` version is not compatible with ProjectA).
   
You have multiple options:
 1. Add `net9-android` Target Framework to ProjectA => this way when ProjectB is built, it will pick net9-android of ProjectA with net9-android of Whisper.net
 2. Workaround: Considering that you already have `Whisper.net.Runtime` only in ProjectB (that is net9-android only) which autmatically loads the native library with `<AndroidNativeLibrary />` , you can skip the initialization of the native library by Whisper.net by calling `RuntimeOptions.LoadedLibrary = RuntimeLibrary.Cpu` from you Android project (before calling any Whisper Factory) => this way, it will be skipped here:
 https://github.com/sandrohanea/whisper.net/blob/38a817cc5d59fc477c77b0bd8ce690bb7ec10f54/Whisper.net/LibraryLoader/NativeLibraryLoader.cs#L31

**Comment by steve3p0** [comment]
Thanks I got it resolved!  I can't pinpoint exactly what I did, other to say I created several .NET 8 and .NET 9 template projects and added Whisper.net and something eventually tool.

Thank you!
